repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
        stages: [ commit ]
  - repo: local
    hooks:
      - id: prettier-lint
        language: system
        stages: [pre-commit]
        pass_filenames: true
        name: prettier lint
        entry: prettier --check
        types_or:
          - "javascript"
          - "ts"
        files: ^(lib|test|cli)/
      - id: eslint
        language: system
        stages: [pre-commit]
        pass_filenames: true
        name: eslint
        entry: npx eslint --color --cache
        types_or:
          - "javascript"
          - "ts"
        files: ^(lib|test|cli)/
