sudo: false
dist: bionic
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 12
script:
  - ./lintVerifier.sh
  - npm test
  - npm run test:bin
after_success:
  - npx semantic-release
branches:
  only:
    - master
