version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1.0

defaults: &defaults
  docker:
    - image: cimg/node:18.17
  working_directory: ~/broker
filter-tags-only: &filter-tags-only
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/
filter-dev-branch-only: &filter-dev-branch-only
  filters:
    branches:
      only: /dev\/.*/

commands:
  dockerhub-login:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Log in to a Docker registry
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  dockerhub-logout:
    steps:
      - run:
          name: Logout from a Docker registry
          command: docker logout
  prepare-dev-package-metadata:
    steps:
      - run:
          name: Prepare package.json and metadata.json for dev images
          command: |
            cd dockerfiles/.scripts && source prepare.sh

jobs:
  install-npm-packages:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/broker
      - run:
          name: Lint
          command: npm run lint
  lint-json-samples:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint JSON templates
          command: ./lintVerifier.sh
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/broker
      - run:
          name: Run tests
          command: npm test && npm run test:bin
  build-and-push-docker-image:
    <<: *defaults
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: 1
    parameters:
      docker_image_name:
        type: string
      docker_image_tag:
        type: string
      docker_file:
        type: string
    steps:
      - checkout
      - dockerhub-login
      - run:
          name: Build and push Docker image
          command: |
            IMAGE_NAME=<< parameters.docker_image_name >>
            IMAGE_TAG=${CIRCLE_TAG/v/''}-<< parameters.docker_image_tag >>
            IMAGE_TAG_LATEST=<< parameters.docker_image_tag >>
            [[ "$IMAGE_NAME" == "snyk/ubuntu" ]] && export IMAGE_TAG=<< parameters.docker_image_tag >>
            [[ "$IMAGE_NAME" == "snyk/ubuntu" ]] && export IMAGE_TAG_LATEST=<< parameters.docker_image_tag >>

            echo "Building Broker image $IMAGE_NAME:$IMAGE_TAG..."
            docker build --tag $IMAGE_NAME:$IMAGE_TAG --file << parameters.docker_file >> .
            echo "Pushing Broker image $IMAGE_NAME:$IMAGE_TAG..."
            docker push $IMAGE_NAME:$IMAGE_TAG

            echo "Tagging Broker image $IMAGE_NAME:$IMAGE_TAG_LATEST.."
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG_LATEST
            echo "Pushing Broker image $IMAGE_NAME:$IMAGE_TAG_LATEST..."
            docker push $IMAGE_NAME:$IMAGE_TAG_LATEST
      - dockerhub-logout
  build-and-push-dev-docker-image:
    <<: *defaults
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: 1
    parameters:
      docker_image_name:
        type: string
      docker_image_tag:
        type: string
      docker_file:
        type: string
    steps:
      - checkout
      - dockerhub-login
      - prepare-dev-package-metadata
      - run:
          name: Build and push Docker dev image
          command: |
            echo "Building Broker image << parameters.docker_image_name >>:<< parameters.docker_image_tag >>..."
            docker build --tag << parameters.docker_image_name >>:<< parameters.docker_image_tag >> --file << parameters.docker_file >> .
            echo "Pushing Broker image << parameters.docker_image_name >>:<< parameters.docker_image_tag >>..."
            docker push << parameters.docker_image_name >>:<< parameters.docker_image_tag >>
      - dockerhub-logout
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/broker
      - run:
          name: Release to GitHub
          command: npm i @semantic-release/exec pkg --save-dev && npx semantic-release@19.0.5

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: broker-alerts

      - install-npm-packages:
          name: Install NPM packages
          requires:
            - Scan repository for secrets

      - lint-json-samples:
          name: Lint JSON samples
          requires:
            - Install NPM packages

      - lint:
          name: Lint
          requires:
            - Install NPM packages

      - test:
          name: Test
          requires:
            - Install NPM packages

      - release:
          name: Release to GitHub and NPM
          context: nodejs-lib-release
          requires:
            - Test
          filters:
            branches:
              only:
                - master

  Release Docker images:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: broker-alerts
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /dev\/.*/

      - build-and-push-docker-image:
          name: Build snyk/ubuntu image
          context: team-broker-docker-hub
          requires:
            - Scan repository for secrets
          docker_image_name: snyk/ubuntu
          docker_image_tag: latest
          docker_file: dockerfiles/ubuntu/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build snyk/ubuntu image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Scan repository for secrets
          docker_image_name: snyk/ubuntu
          docker_image_tag: nlatest
          docker_file: dockerfiles/ubuntu/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build artifactory image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: artifactory
          docker_file: dockerfiles/artifactory/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build azure-repos image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: azure-repos
          docker_file: dockerfiles/azure-repos/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build bitbucket-server image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: bitbucket-server
          docker_file: dockerfiles/bitbucket-server/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build github-com image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: github-com
          docker_file: dockerfiles/github-com/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build github-enterprise image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: github-enterprise
          docker_file: dockerfiles/github-enterprise/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build gitlab image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: gitlab
          docker_file: dockerfiles/gitlab/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build jira image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: jira
          docker_file: dockerfiles/jira/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build nexus image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: nexus
          docker_file: dockerfiles/nexus/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build nexus2 image
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image
          docker_image_name: snyk/broker
          docker_image_tag: nexus2
          docker_file: dockerfiles/nexus2/Dockerfile
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build artifactory image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: artifactory-nlatest
          docker_file: dockerfiles/artifactory/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build azure-repos image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: azure-repos-nlatest
          docker_file: dockerfiles/azure-repos/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build bitbucket-server image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: bitbucket-server-nlatest
          docker_file: dockerfiles/bitbucket-server/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build github-com image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: github-com-nlatest
          docker_file: dockerfiles/github-com/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build github-enterprise image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: github-enterprise-nlatest
          docker_file: dockerfiles/github-enterprise/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build gitlab image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: gitlab-nlatest
          docker_file: dockerfiles/gitlab/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build jira image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: jira-nlatest
          docker_file: dockerfiles/jira/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build nexus image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: nexus-nlatest
          docker_file: dockerfiles/nexus/Dockerfile.nlatest
          <<: *filter-tags-only

      - build-and-push-docker-image:
          name: Build nexus2 image (nlatest)
          context: team-broker-docker-hub
          requires:
            - Build snyk/ubuntu image (nlatest)
          docker_image_name: snyk/broker
          docker_image_tag: nexus2-nlatest
          docker_file: dockerfiles/nexus2/Dockerfile.nlatest
          <<: *filter-tags-only

      - approve-from-team-broker:
          name: team-broker-approval
          type: approval
          context: team-broker-approval-only
          requires:
            - Scan repository for secrets

      - approve-build-github-com-dev:
          name: github-com-dev image
          type: approval
          requires:
            - team-broker-approval
          <<: *filter-dev-branch-only

      - build-and-push-dev-docker-image:
          name: Build github-com image (dev)
          context: team-broker-docker-hub
          requires:
            - github-com-dev image
          docker_image_name: snyk/broker
          docker_image_tag: github-com-dev
          docker_file: dockerfiles/github-com/Dockerfile.dev
          <<: *filter-dev-branch-only

      - approve-build-gitlab-dev:
          name: gitlab-dev image
          type: approval
          requires:
            - team-broker-approval
          <<: *filter-dev-branch-only

      - build-and-push-dev-docker-image:
          name: Build gitlab image (dev)
          context: team-broker-docker-hub
          requires:
            - gitlab-dev image
          docker_image_name: snyk/broker
          docker_image_tag: gitlab-dev
          docker_file: dockerfiles/gitlab/Dockerfile.dev
          <<: *filter-dev-branch-only
